CREATE OR REPLACE TRIGGER TRG_AD_ITENS_FORNECEDOR
  BEFORE UPDATE ON ITENS
  FOR EACH ROW

DECLARE
  vMaquina  VARCHAR2(64);
  vUsuario  VARCHAR2(64);
  vPrograma VARCHAR2(64);
  vUsername VARCHAR2(64);
  P_CLASSE_CONTABIL VARCHAR2(64);
  P_CODTRIBUTACAO VARCHAR(64);
  P_NCM VARCHAR(64);

BEGIN

IF :NEW.COD_TRIBUTACAO != :OLD.COD_TRIBUTACAO
THEN
   SELECT DISTINCT machine, osuser, username, program
   INTO vMaquina, vUsuario, vUsername, vPrograma
   FROM v$session
   WHERE audsid = userenv('sessionid');

  SELECT DESCRICAO
  INTO P_CLASSE_CONTABIL
  from ITENS_CLASSE_CONTABIL
  WHERE COD_CLASSE_CONTABIL = :OLD.COD_CLASSE_CONTABIL;

  SELECT DESCRICAO
  INTO P_CODTRIBUTACAO
  FROM ITENS_TRIBUTACAO
  WHERE COD_TRIBUTACAO = :OLD.COD_TRIBUTACAO;

  SELECT NCM
  INTO P_NCM
  FROM ITENS_FORNECEDOR
  WHERE COD_ITEM = :OLD.COD_ITEM;

  INSERT INTO AD_ITENS_FORNECEDOR
    (DATA_ALTERACAO,
     SERVER,
     USUARIO_SO,
     USUARIO_SISTEMA,
     PROGRAMA,
     COD_ITEM,
     DESCRICAO,
     COD_TRIBUTACAO,
     COD_CLASSE_CONTABIL,
     NCM)
  VALUES
    (sysdate,
     vMaquina,
     vUsuario,
     vUsername,
     vPrograma,
     :OLD.COD_ITEM,
     :OLD.DESCRICAO,
     P_CODTRIBUTACAO,
     P_CLASSE_CONTABIL,
     P_NCM);
END IF;
END;
